# Generated by Django 2.2.11 on 2021-07-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml2_pro_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlprovider',
            name='idp_x509_signing_key',
            field=models.TextField(blank=True, help_text='A PEM encoded public certificate provided by your Identity Provider.', null=True, verbose_name='IdP Certificate Signing'),
        ),
    ]
